# Generated by Django 6.1 on 2026-09-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='applied_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='periods_covered',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
