# Generated by Django 6.1 on 2026-09-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestcategory',
            name='keywords',
            field=models.TextField(blank=True, help_text='Enter keywords separated by commas.', null=True),
        ),
    ]
