# Generated by Django 6.1 on 2026-09-11 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_requests', '0002_requestcategory_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal name, e.g. location or number_of_cameras.', max_length=150)),
                ('question', models.CharField(help_text='Question that WhatsApp should ask the customer.', max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('yes_no', 'Yes / No'), ('choice', 'Choice')], default='text', max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=1, help_text='Order in which this information should be collected.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_fields', to='business_requests.requestcategory')),
            ],
            options={
                'ordering': ['category', 'order', 'id'],
            },
        ),
    ]
