# Generated by Django 6.1 on 2026-09-18 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_requests', '0005_alter_department_options_department_organization_and_more'),
        ('organizations', '0002_country_alter_organization_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='organizations.organization'),
        ),
    ]
