# Generated by Django 6.1 on 2026-09-26 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_requests', '0006_alter_department_organization'),
        ('organizations', '0002_country_alter_organization_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestcategory',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_categories', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='requestcategory',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
