# Generated by Django 6.1 on 2026-09-26 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_requests', '0007_requestcategory_organization_and_more'),
        ('organizations', '0002_country_alter_organization_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestcategory',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_categories', to='organizations.organization'),
        ),
    ]
