# Generated by Django 6.1 on 2026-10-08 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_requests', '0008_alter_requestcategory_organization'),
        ('products', '0003_product_request_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessrequest',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_requests', to='products.product'),
        ),
    ]
