# Generated by Django 6.1 on 2026-09-17 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_country_alter_organization_language_and_more'),
        ('whatsapp', '0002_alter_conversation_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppBusinessAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waba_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('business_manager_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('connected', 'Connected'), ('disconnected', 'Disconnected'), ('suspended', 'Suspended'), ('error', 'Error')], default='pending', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_business_accounts', to='organizations.organization')),
            ],
            options={
                'ordering': ['organization__name', 'business_name'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('phone_number', models.CharField(max_length=30)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('verified_name', models.CharField(blank=True, max_length=255, null=True)),
                ('country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('quality_rating', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('connected', 'Connected'), ('disconnected', 'Disconnected'), ('suspended', 'Suspended'), ('error', 'Error')], default='pending', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_phone_numbers', to='organizations.organization')),
                ('whatsapp_business_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='whatsapp.whatsappbusinessaccount')),
            ],
            options={
                'ordering': ['organization__name', 'phone_number'],
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='whatsapp_phone_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='whatsapp.whatsappphonenumber'),
        ),
        migrations.AddConstraint(
            model_name='whatsappphonenumber',
            constraint=models.UniqueConstraint(fields=('organization', 'phone_number'), name='unique_org_whatsapp_phone'),
        ),
    ]
