# Generated by Django 6.1 on 2026-09-17 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_country_alter_organization_language_and_more'),
        ('whatsapp', '0003_whatsappbusinessaccount_whatsappphonenumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(blank=True, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('connected', 'Connected'), ('disconnected', 'Disconnected'), ('error', 'Error')], default='pending', max_length=30)),
                ('last_connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_connections', to='organizations.organization')),
                ('whatsapp_business_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection', to='whatsapp.whatsappbusinessaccount')),
            ],
            options={
                'ordering': ['organization__name'],
            },
        ),
    ]
